# Site settings
name: Less Or More
email: wliang0371@163.com
author: Jacky Wang
url: http://fuxiao511.github.com
github: https://github.com/fuxiao511/
baseurl: ""
resume_site: 
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
permalink: /:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fuxiao511
highlighter: rouge

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : fuxiao511
    disqus :
        short_name : fuxiao511
